export const dimensionDef : string = `A dimension will contain categorical dimension values (attributes) that are qualitative and subjective to the user. This means there is no right answer for selecting a dimension value. The user should be able to select any dimension value depending on their preference. The dimensions must not be an evaluation of how good the writing is. All responses are assumed to be the best writing generated by you.\n\n`
//  `一个维度将包含定性的、主观的类别维度值（属性），这些属性是基于用户的主观感受的。这意味着在选择维度值时没有正确答案。
// 用户应根据自己的偏好选择任何维度值。这些维度不应对写作质量进行评价。所有的回答都被假定为由你生成的最佳写作。\n\n`

export const dimensionConclusion : string = `Even though I encourage you to use some of these examples if best fitting, I highly recommend that I also get unique and orthogonal dimensions.\n\n`
//  `尽管我鼓励你使用一些最合适的示例，但我强烈建议你也提供独特且正交的维度。\n\n`

export const nominalDimensionDef : string = dimensionDef + `A nominal dimension will contain dimension values that do not have a particular order and are up to the user's selection. Some nominal dimensions that I would want are Tone, Setting, Style, or Perspective. I do NOT want Length, Grammar, Quality, or Clarity.\n\n` + dimensionConclusion;

// `一个名义维度将包含没有特定顺序的维度值，用户可以自由选择。我希望的一些名义维度包括语气、背景、风格或视角。我不希望看到的维度有长度、语法、质量或清晰度。\n\n` + dimensionConclusion;


export const ordinalDimensionDef : string = dimensionDef + `An ordinal dimension will contain dimension values measured in an order (least, less, neutral, more, most). The type of dimensions I want are ones that are of a single key property that the user may want more of or less of depending on their preference. Some ordinal dimensions that I would want are Concreteness, Realism, or Subjectivity. I do NOT want Quality, Creativity, or Length.\n\n` + dimensionConclusion;

// `一个序列维度将包含按顺序排列的维度值（例如最少、较少、中立、较多、最多）。我希望的序列维度是那些用户可能根据个人喜好希望更多或更少的单一关键属性。
// 一些我希望的序列维度包括具体性、现实主义或主观性。我不希望看到的维度有质量、创造力或长度。\n\n` + dimensionConclusion;
